### ISSUE TITLE
[Feature Request] Please add a config option to change the position.

### ISSUE THREAD

**Issue by ProsperCraft** [Geek202/LookAtThat#2]
**Describe the bug**
I would like to put it in the top center by default in my packs.

Currently overlays Biome Info-
![2020-02-20_19 12 39](https://user-images.githubusercontent.com/4427684/74999542-2763f800-5419-11ea-83fb-845615da0197.png)

**Comment by Tom-The-Geek** [comment]
Thanks for the suggestion!

I will look into this as it was a feature I originally considered adding and I also think it would be a great addition.

I will add it to the 1.15.2 version first and, if needed, I can add it to the 1.14.4 version as well.

**Comment by kreezxil** [comment]
yeah top center would be cool. 

But if you're going to do that, just allow the player to reposition it anywhere. Top Left, Top Center, Top Right, Center Left, Center Right, Bottom Left, Bottom Right
or borrow code from Xaero's Minimap for true placement.

I'd be happy with top center tho. will wait for that to be added and the will gladly remove HWYLA from foreshadowing pack ... **reason** hwyla supports both fabric and forge in the same cf mod repository, this makes it a pita to update modpacks using it because you don't know if the download will grab fabric or not forcing you to look at the mod page.

**Comment by Tom-The-Geek** [comment]
Have added overlay centering to GitHub and will push a new update to CurseForge tomorrow.

**Comment by Tom-The-Geek** [comment]
Pushed to CurseForge
